const express=require('express'),path=require('path'),fs=require('fs');
const session=require('express-session'),methodOverride=require('method-override');
require('./db');
const app=express();
const UP=path.join(__dirname,'uploads');try{fs.mkdirSync(UP,{recursive:true});}catch(_){}
app.set('view engine','ejs');app.set('views',path.join(__dirname,'views'));
app.use(express.urlencoded({extended:true}));app.use(methodOverride('_method'));
app.use(express.static(path.join(__dirname,'public')));app.use('/uploads',require('express').static(path.join(__dirname,'uploads')));
app.use(session({secret:'nirnoy-secret',resave:false,saveUninitialized:false}));
app.use((req,res,next)=>{res.locals.user=req.session.user||null;res.locals.flash=req.session.flash||null;delete req.session.flash;next();});
app.use(require('./routes/auth'));
app.use(require('./routes/admin_manage'));
app.use(require('./routes/migrate'));
app.use(require('./routes/migrate_step4'));
app.use(require('./routes/dev_reset'));
app.use(require('./routes/migrate_step5'));
app.use(require('./routes/migrate_step6'));
app.use(require('./routes/migrate_step8'));
app.use(require('./routes/migrate_step9'));
app.use(require('./routes/migrate_step15'));
app.use(require('./routes/dev_seed_demo'));
app.use(require('./routes/files'));
app.use(require('./routes/doctor'));
app.use(require('./routes/doctors'));
app.use(require('./routes/appointments'));
app.use(require('./routes/doctor_portal'));
app.use(require('./routes/booking'));
app.use(require('./routes/clinics'));
app.use(require('./routes/patients'));
app.get('/',(req,res)=>res.render('home'));
app.get('/debug/me',(req,res)=>{res.type('json').send(JSON.stringify(req.session.user||{},null,2));});
app.get('/debug/outbox',(req,res)=>{const p=path.join(__dirname,'outbox.log');if(!fs.existsSync(p))return res.type('text').send('(empty)');res.type('text').send(fs.readFileSync(p,'utf8'));});
require('./jobs');

app.listen(3000,()=>console.log('Nirnoy 2.0 running at http://localhost:3000'));
